### ISSUE TITLE
WHISTLIST: Punto de venta no depender de website

### ISSUE THREAD

**Issue by celm1990** [dansanti/l10n_cl_dte_point_of_sale#12]
En la V11 mejoraron el portal, y no es necesario instalar el modulo de website para poder crear paginas web, Para el tema de consultar las boletas podriamos usar el portal. Si hago un PR para este tema podrias aceptarlo????

**Comment by dansanti** [comment]
hola, No había visto ese detalle, si es posible crear páginas públicas sin el portal y siga cumpliendo con la normativa, bueno

**Comment by celm1990** [comment]
Acabo de subir un cambio para mejorar el diseño de la boleta, le quite la dependencia a website y se agrego dependencia a portal, por favor revisar el commit 359fdc06995b4256b03c0e94d9335f2eade9d968

Conversando con un cliente  me indicaba que es mejor que no solo pidas el numero de folio, sino datos como la fecha y el total, xq como estaba antes cualquiera puede encontrar folios al azar y obtener un documento tributario. Asi le ponemos un poco mas de seguridad.
Ademas con el soporte de boletas exentas, aca agregamos que el tipo de documento sea configurable al momento de consultar el documento, antes estaba quemado en el codigo y cuando tenia boletas exenta o afecta con el mismo folio, solo me traia una, y no se podia obtener la otra por ningun motivo.

Te muestro un antes y un despues:
**ANTES**, pagina de consultar boleta
![image](https://user-images.githubusercontent.com/7775116/35176456-178a16f6-fd47-11e7-9bff-e85f7bd32d56.png)

**DESPUES**, pagina de consultar boletas
![image](https://user-images.githubusercontent.com/7775116/35176459-28e86c22-fd47-11e7-866b-7c45eead0adf.png)

**ANTES**, pagina de boleta encontrada:
![image](https://user-images.githubusercontent.com/7775116/35176470-3ce43b7a-fd47-11e7-8e77-6edab2f1b94a.png)

**DESPUES** pagina de boleta encontrada
![image](https://user-images.githubusercontent.com/7775116/35176505-8bb3cdd8-fd47-11e7-96fb-5fca15cd330e.png)

Cuando una boleta no se encontraba, no indicaba nada, ahora se mostrara esta ventana:
![image](https://user-images.githubusercontent.com/7775116/35176531-b81d91ce-fd47-11e7-8582-a44ded8b715d.png)

Falta programar el boton de descargar el PDF, esto xq hay q hacer el reporte en Qweb.

**Comment by celm1990** [comment]
Como dato adicional, te invito a revisar este commit https://github.com/celm1990/odoo/commit/6c3b4dfbfac42fb5834c2158f368d745fcdf1ce5 aca agrego una funcionalidad importante que facilita las busquedas en campos datetime pasando solo la parte de fecha y el sistema se encarga de completar la hora para tomar el dia entero. Eso sirve para buscar en los pedidos del punto de venta que es un campo datetime y desde el portal solo le pasamos la fecha.

**Comment by celm1990** [comment]
Se hizo merge, cierro issue
