### ISSUE TITLE
Firma en PY y JS Diferentes

### ISSUE THREAD

**Issue by celm1990** [dansanti/l10n_cl_dte_point_of_sale#2]
Al realizar una venta en el TPV, sale el error que las firmas son diferentes, revisando el codigo en python usan el campo name del producto, pero en JS usa display_name(pudiendo tener el codigo del producto y los atributos en caso de usar variantes), pero porque no se usa el mismo campo en PY o JS?????.

El problema esta en los archivos [https://github.com/dansanti/l10n_cl_dte_point_of_sale/blob/9.0/models/point_of_sale.py](url) linea 1134-1136
[https://github.com/dansanti/l10n_cl_dte_point_of_sale/blob/9.0/static/src/js/pos_dte.js](url)  linea 130

**Comment by dansanti** [comment]
de hecho e todo lo contrario, el campo name enpy, puede contener el código interno, por eso más abajo lo quito.

Si en ese lugar hay un ligero bug que se da por el ordenamiento de los productos, por alguna razón al meter los proudctos en un for, y luego tratar de quitar el códgo interno del producto, odoo o python se quedan "pegados" con el ćodigo interno anterior, entonces no ejecutan el replace. así de que ahi hay un bug ( para cuando se usa default_code)

**Comment by dansanti** [comment]
fixed via https://github.com/dansanti/l10n_cl_dte_point_of_sale/commit/f736a536ccfe09f65c9f41029a740622eb28e98b
