### ISSUE TITLE
[WISHLIST] Punto de Venta multitienda con visibilidad a usuarios por tienda

### ISSUE THREAD

**Issue by celm1990** [dansanti/l10n_cl_dte_point_of_sale#20]
El sistema permite crear multiples TPV en el sistema, pero en un escenario de una empresa que tenga muchas tiendas en todo el pais y se desee que los usuarios de cada tienda vean solo sus TPV correspondientes a su tienda y no los de otras tiendas, eso no tiene soporte el sistema de base, en V8 hacia atras en el usuario habia la posibilidad de configurar los TPV asignados a ese usuario, pero eso lo eliminaron.
Para nosotros si es importante tener esa funcionalidad, de poder en el usuario poder configurar los TPV a los que puede acceder y agregar reglas de registro para filtrar datos.
Abro este bug con la finalidad de poder agregar mas funcionalidades al TPV que realmente le faltan y considero que son necesarios, como un reporte Z al cerrar sesion.
La gran pregunta es si tienes planes de agregar esas funcionalidades o ya las tienes?, O si no las tienes y nosotros las proponemos, la aceptarias?. Hay modulos comunity tambien que podriamos tomar, pero aqui me gustaria escuchar tu punto de vista respecto a mejorar el TPV.

**Comment by dansanti** [comment]
tengo claro eso, pero estoy recién viendo otras cosas, las empresas que he visto con multisucursal estan en 9 aún con modificaciones a odoo, tengo que revisar al detalle. a todo esto esto es una petición hacia odoo, de hecho es una configuración que se agrega sobre las restricciones desde el menú technico en ajustes, no va al caso acá.
 Por ahora el roadmap es dejar estable lo básico, terminar factura exportación, terminar factura de compra, agregar formato ticket por posbox factura, una vez estabilizados esos temas, se pasan a otros ya más específicos y avanzados

**Comment by celm1990** [comment]
Por favor revisar el PR #21 si es posible hacer el merge. Sino me avisas para cerrar el issue sin problemas

**Comment by celm1990** [comment]
Cierro esto xq no se acepto merge, y esa funcionalidad se tendra en un modulo independiente
