### ISSUE TITLE
[WHISTLIST] Separar en varios archivos el codigo, segun funcionalidad

### ISSUE THREAD

**Issue by celm1990** [dansanti/l10n_cl_dte_point_of_sale#24]
Este no es un bug, pero me gusta seguir las guideslines de odoo, en cuanto a tener un archivo por cada clase, para el punto de venta el codigo de JS en el modulo base esta separado en archivos:
**modes.js** > clases backbone para los modelos(pos, pos_order, pos_order_line, pos_payment, etc)
**screen.js** > clases relacionadas a la interaccion del usuario(PaymentScreen, ClientScreen, Receipt, etc)
**popups.js** > clases relacionadas a ventas de mensajes al usuario, etc
Lo que pretendo es separar en varios archivos segun las clases a heredar/extender. Las razones seria:
1.-En el modulo l10n_cl_dte_point_of_sale tenemos un solo modulo que tiene clases de muchas cosas(de models, de screen, de receipt, etc) lo cual dificulta su revision y que hay que buscar en un mar de codigo.
2.- Hay lugares donde segun mi punto de vista, se hace mala herencia de codigo
[Aqui un ejemplo](https://github.com/dansanti/l10n_cl_dte_point_of_sale/blob/11.0/static/src/js/pos_dte.js#L488-L540), deberia heredarse de la clase completa y sobreescribir/reemplazar la funcion push_order, pero la forma como lo haces no me parece la mejor, se deberia extender la clase, y ahi extender/reemplazar la funcion(es) que se deseen
3.- Hay lugares donde por la [identacion de codigo](https://github.com/dansanti/l10n_cl_dte_point_of_sale/blob/11.0/static/src/js/pos_dte.js#L588-L599), dificulta su lectura, no se que IDE usas para desarrollo, pero deberiamos tener el codigo bien formateado e identado que a simple vista se pueda leer. 

Mi problema es que de cierta manera soy obsesionado con tener un codigo limpio que sea facil de leer y sobre todo de mantener. Espero que podamos mejorar este tema aca, se que estas en otras prioridades, pero esto lo podria hacer yo, y no pretendo cambiar una linea de codigo, solo separar en archivos independientes, mejorar la identacion del texto.

Me gustaria escuchar tus comentarios

**Comment by dansanti** [comment]
- Si en js  ha sido complejo ordenarlo, yo he tratdo, pero siempre se desordena.
- hayun cambio que estoy pensando en hacer en las secuencias, esto debido a que en odoo 11, el módulo account_accountant es enterprise, esto hace que journal_id esté oculto, etonces, voy dejar que cada pos pueda configurar secuencias directasy que los journals también, pero sean caf a partes al de  pos

**Comment by celm1990** [comment]
Bueno, entonces podria hacer ese cambio yo de ordenar el codigo en JS, no cambiar nada, solo ordenarlo y separarlo en archivos independientes segun su funcionalidad.

Con respeccto a lo de journal_id, tienes razon no es visible xq el modulo account_accountant es enterprise, pero podriamos sobreescribir la funcion y hacerlo visible cuando el modulo account este instalado, eso seria facil creo yo, solo reemplazar [esta funcion](https://github.com/odoo/odoo/blob/11.0/addons/point_of_sale/models/pos_config.py#L167-L170)

**Comment by celm1990** [comment]
Se hizo PR para separar los archivos JS y se hizo merge de ese PR, esto soluciona el punto 1 y 3.

Para el segundo punto, se hizo este PR #27 , aca se hereda de la clase y se agregan/extienden las funciones necesarias.

No se cambia codigo, por favor hacer merge, necesito ese cambio para corregir un bug que detecte cuanddo tienes multicaf que te lo voy a explicar en otro bug.

**Comment by celm1990** [comment]
Se realizo merge, cierro issue
