### ISSUE TITLE
Variables no declaradas

### ISSUE THREAD

**Issue by celm1990** [dansanti/l10n_cl_dte_point_of_sale#4]
Al querer enviar documentos al SII, salen errores de variables no declaradas, se corrigen en el commit [https://github.com/celm1990/l10n_cl_dte_point_of_sale/commit/16bde43f1b5a47ef2f8f463c5a4d3fe701da1be7](https://github.com/celm1990/l10n_cl_dte_point_of_sale/commit/16bde43f1b5a47ef2f8f463c5a4d3fe701da1be7)

Tengo varias cosas diferentes al repo original, por ello no hago un PR

**Comment by dansanti** [comment]
Si, debido a que el sii, no pide enviar las boletas, entonces no  ha sido usado, lo que si ,ese cambio está hecho en mi repo, porque se aplica para las NC, (refund), hay varias cosas que he cambiado , para diferenciar un orden desde POS o desde BO
