### ISSUE TITLE
Salto de secuencias al generar ventas desde el pos

### ISSUE THREAD

**Issue by celm1990** [dansanti/l10n_cl_dte_point_of_sale#5]
El consumo de folio solo debería generarse cuando no hay numero, no antes, para evitar consumir folios innecesarios, el error esta en la linea [861](https://github.com/celm1990/l10n_cl_dte_point_of_sale/blob/9.0/models/point_of_sale.py#L861)

La generacion del secuencial deberia ir dentro del if, no antes

**Comment by dansanti** [comment]
si , tienes razón, ese if no lo actualicé en conjunto a la diferenciación de caf o no caf
