### ISSUE TITLE
Error al tomar el siguiente numero de la secuencia

### ISSUE THREAD

**Issue by celm1990** [dansanti/l10n_cl_dte_point_of_sale#6]
Al abrir sesion en el pos, se toma la primera secuencia para llenar el campo Folio de comienzo, pero se usa el campo number_next de ir.sequence, este campo solo es valido si es una secuencia estandar, pero para las secuencias gap ese campo siempre sera 1, por lo que es mejor usar el campo number_next_actual que se toma segun el tipo de secuencia

[linea 36](https://github.com/celm1990/l10n_cl_dte_point_of_sale/blob/9.0/models/pos_session.py#L36)

este campo si se usa en la linea [49](https://github.com/celm1990/l10n_cl_dte_point_of_sale/blob/9.0/models/pos_session.py#L49)

deberian ser el mismo campo en ambos lados

**Comment by dansanti** [comment]
originalmente, había puesto ese campo, pero genera un problema,   en el
caso de que cierrres una sesión sin movimiento, la.siguiente sesión debiera
tomar el mismo número de la anterior, pero no ocurre con ese campo, ya que
odoo te lo incrementa ,

también creo me daba error cuando hacia el cierre, se saltaba un folio, al
inició se la sesión, ya que nuevamente hace un incremento

**Comment by celm1990** [comment]
Hice pruebas al abrir y cerrar sesion sin generar pedidos y no se salta la secuencia, creo que el problema que me comentas va relacionado con el otro bug  [5](https://github.com/dansanti/l10n_cl_dte_point_of_sale/issues/5), que ahi es q salta la secuencia innecesariamente

**Comment by dansanti** [comment]
por qué dices que es innecesario?, la lógica es de  que si es válido, consume folio, sino "no lo hace", porque debo poner el next_by_id() debajo de _timbrar() para que en caso de error de timbraje, no consuma folio.

El caso de uso que te menciono es distinto, no tiene relacón a #5 .


Además de que tienes que mirar de que number_next_actual == number_next, 

```
    def _get_number_next_actual(self):
        '''Return number from ir_sequence row when no_gap implementation,
        and number from postgres sequence when standard implementation.'''
        for element in self:
            if element.sequence_id.implementation != 'standard':
                element.number_next_actual = element.number_next
```
