### ISSUE TITLE
Errores varios al crear pedido de venta desde backend(Punto de venta)

### ISSUE THREAD

**Issue by celm1990** [dansanti/l10n_cl_dte_point_of_sale#7]
Cuando se quiere crear un pedido desde el backend(no desde la interfaz web) salen muchos errores porque hay funciones o campos no declarados, la mayoria de codigo deduzco que es tomado de account.invoice(modulo l10n_cl_invoice), pero en este modulo no existen, detallo algunos campos y funciones que he detectado que no existen:

La funcion principal que tiene problemas es 
def _get_available_journal_document_class(self, default=None):

Aqui se usa el campo inv.use_documents que no existe en pos.order, en account.invoice es un related del diario, pero aca no existe.
Luego se llama a la funcion get_operation_type que tampoco existe(en invoice si existe).
Otra funcion es get_valid_document_letters que se llama pero no existe.

Todos estos errores no permiten crear un pedido del punto de venta en el backend, por favor indicar como solucionar eso.

**Comment by dansanti** [comment]
Así es , no he probado aún hacer por backend pedidos, solamente refund.

**Comment by dansanti** [comment]
closed via :https://github.com/dansanti/l10n_cl_dte_point_of_sale/commit/d70f7e47f125bb81b7349c32d673f22421c13038
