### ISSUE TITLE
Secuencia de Boletas en el POS se avanza asi no sea Boleta o Factura

### ISSUE THREAD

**Issue by celm1990** [dansanti/l10n_cl_dte_point_of_sale#9]
En este commit e58ef26b12cb1781dfdc7c9716b4e2dfc7d25e35 se introdujo un concepto importante, que permite ser dinamico en el POS con respecto al tipo de documento a emitir(Boleta o Factura), pero si el usuario desmarca el boton, no se emite ni Boleta ni Factura, se emite un pedido normal del pos, no se genera numero de folio ni se timbra en el POS, sin embargo en el backend se avanza la secuencia por ende se avanza en el siguiente numero de folio, esto lo considero un error. Adjunto imagenes que explican el proceso que hago:

Tengo un CAF cargado con 200 folios
La configuracion del TPV es la siguiente

![image](https://user-images.githubusercontent.com/7775116/34962201-bf7c398c-fa10-11e7-8866-83b0b6c168f0.png)

En el dashboard sale que el proximo numero es el 15, correcto.

![image](https://user-images.githubusercontent.com/7775116/34962219-d15f36ea-fa10-11e7-8703-f0650982af44.png)

Cargo la sesion y hago una venta de cualquier producto
![image](https://user-images.githubusercontent.com/7775116/34962242-ea3b72dc-fa10-11e7-8a61-f6300500a5c4.png)

Aca **desactivo el Boton Boleta** y no me consume folios ni de boleta ni de factura, chevere se imprime el ticket normal

![image](https://user-images.githubusercontent.com/7775116/34962266-09f9a10c-fa11-11e7-812f-eb5bf22e6cd7.png)

Pero al volver a ver el dashboard, sale como proximo numero el 16  aun cuando no se uso el folio(si sigo vendiendo sin seleccionar el boton boleta en el TPV, se seguira consumiendo folios en el backend
![image](https://user-images.githubusercontent.com/7775116/34962290-208267f6-fa11-11e7-986d-d01ea7a506b4.png)

El pedido tiene como Folio 0
![image](https://user-images.githubusercontent.com/7775116/34962372-6bd08c1a-fa11-11e7-81ef-5b4b03ace550.png)

Pero a nivel de secuencias se avanzo al siguiente numero, eso pasa SIEMPRE que se no se seleccione el boton en el TPV

**Comment by dansanti** [comment]
te ocurre este error también en ff ? https://github.com/odoo/odoo/issues/22211
